describe clientes;
create database mascota;
create database motos;
use motos;
create table fabricante (id_fabricante int (3), nombre varchar (12), pais varchar (20));
create table moto ( id_moto int(4), referencia  varchar(20), modelo int (4), marca varchar(10));
create table propietario ( id_propietario int(11), nombre varchar (12), apellido varchar (12), telefono int (15));
create table mantenimiento ( id_ingreso int(5), id_moto int(4), id_propietario int(11), fecha date, valor_total int(10)); 
show databases;
show tables;
insert into moto (id_moto, referencia, modelo, marca) values ( 1,'cr4', 2022, 'akt');
select id_moto, referencia, modelo, marca from moto; 
insert into moto (id_moto, referencia, modelo, marca) values ( 2,'fz', 2021, 'yamaha');
update moto set referencia='cr5' where referencia= 'cr4';
